---
title: "POL 390 Problem Set 2"
author: "Joel Perriard"
date: "2023-06-11"
output: html_document
---
#
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tmap)
library(leaflet)
library(sf)
library(stringr)
library(sp)
library(tidyverse)
library(dplyr)
#install.packages('rgdal')
canada_election_history <- read.csv("http://www.lop.parl.gc.ca/Content/LOP/OpenData/HFER_e.csv")
write.csv(canada_election_history, "canada_election_history.csv")

election_results_41st <- read.csv("2011_Canadian_Federal_Election_Results.csv")

election_results_42nd <- read.csv("2015_Canadian_Federal_Election_Results.csv")

election_results_43rd <- read.csv("2019_Canadian_Federal_Election_Results.csv")

election_results_44th <- read.csv("2021_Canadian_Federal_Election_Results.csv")

election_results_combined <- rbind(election_results_41st, election_results_42nd, election_results_43rd, election_results_44th)

write.csv(election_results_combined, "election_results_total.csv")

election_results_combined <- read.csv("election_results_total.csv")

# on hold for rn. total_data_set 

total_data_set <- read.csv('Final_Data.csv')


```

```{r}
library(leaflet)
library(geojsonio)

# https://data.opendatasoft.com/explore/dataset/georef-canada-province%40public/export/?disjunctive.prov_name_en


library(leaflet)
library(geojsonio)
library(rgdal)
canada <- geojsonio::geojson_read("georef-canada-province@public.geojson", what = "sp")
class(canada)

m <- leaflet(canada) %>%
  setView(-80, 35.8, 2.1) %>%
  addProviderTiles("MapBox", options = providerTileOptions(
    id = "mapbox.light",
    accessToken = Sys.getenv('MAPBOX_ACCESS_TOKEN')))

m %>% addPolygons(
  weight = 2,
  opacity = 1,
  color = "darkgray",
  dashArray = "5",
  fillOpacity = 0.5,
  highlightOptions = highlightOptions(
    weight = 2,
    color = "black",
    dashArray = "1",
    fillOpacity = 1,
    bringToFront = TRUE))


shapefiles_canada_2015 <- read_sf("FED_CA_2_2_ENG.shp")

shapefiles_canada_2019 <- read_sf("FED_CA_2019_EN.shp")

shapefiles_canada_2021 <- read_sf("FED_CA_2021_EN.shp")

tm_shape(shapefiles_canada_2021) +
  tm_polygons()



#3, ANIMATED MAP

urb_anim = tm_shape(canada) + tm_polygons() + 
  tm_shape(total_data_set$Province) + tm_dots(size = "population_millions") +
  tm_facets(along = "year", free.coords = FALSE)

tmap_animation(urb_anim, filename = "urb_anim.gif", delay = 25)


canada <- geojsonio::geojson_read("georef-canada-province@public.geojson", what = "sp")
class(canada)

m <- leaflet(canada) %>%
  setView(-80, 35.8, 2.1) %>%
  addProviderTiles("MapBox", options = providerTileOptions(
    id = "mapbox.light",
    accessToken = Sys.getenv('MAPBOX_ACCESS_TOKEN')))

m %>% addPolygons(
  weight = 2,
  opacity = 1,
  color = "darkgray",
  dashArray = "5",
  fillOpacity = 0.5,
  highlightOptions = highlightOptions(
    weight = 2,
    color = "black",
    dashArray = "1",
    fillOpacity = 1,
    bringToFront = TRUE))






















```
