---
title: "POL 390 Problem Set 2"
author: "Joel Perriard"
date: "2023-06-11"
output: html_document
---
#
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tmap)
library(leaflet)
library(sf)
library(stringr)
library(sp)
library(tidyverse)
library(dplyr)
#install.packages('rgdal')
getwd()
setwd("/Users/hyunmyungchoi/study_R/POL390")
canada_election_history <- read.csv("http://www.lop.parl.gc.ca/Content/LOP/OpenData/HFER_e.csv")
write.csv(canada_election_history, "canada_election_history.csv")

election_results_41st <- read.csv("2011_Canadian_Federal_Election_Results.csv")

election_results_42nd <- read.csv("2015_Canadian_Federal_Election_Results.csv")

election_results_43rd <- read.csv("2019_Canadian_Federal_Election_Results.csv")

election_results_44th <- read.csv("2021_Canadian_Federal_Election_Results.csv")

election_results_combined <- rbind(election_results_41st, election_results_42nd, election_results_43rd, election_results_44th)

write.csv(election_results_combined, "election_results_total.csv")

election_results_combined <- read.csv("election_results_total.csv")

# on hold for rn. total_data_set 

#total_data_set <- read.csv('Final_Data.csv')


```

```{r}
library(leaflet)
library(geojsonio)

# https://data.opendatasoft.com/explore/dataset/georef-canada-province%40public/export/?disjunctive.prov_name_en


library(leaflet)
library(geojsonio)
library(rgdal)
canada <- geojsonio::geojson_read("georef-canada-province@public.geojson", what = "sp")
class(canada)

m <- leaflet(canada) %>%
  setView(-80, 35.8, 2.1) %>%
  addProviderTiles("MapBox", options = providerTileOptions(
    id = "mapbox.light",
    accessToken = Sys.getenv('MAPBOX_ACCESS_TOKEN')))

m %>% addPolygons(
  weight = 2,
  opacity = 1,
  color = "darkgray",
  dashArray = "5",
  fillOpacity = 0.5,
  highlightOptions = highlightOptions(
    weight = 2,
    color = "black",
    dashArray = "1",
    fillOpacity = 1,
    bringToFront = TRUE))


shapefiles_canada_2015 <- read_sf("FED_CA_2_2_ENG.shp")

shapefiles_canada_2019 <- read_sf("FED_CA_2019_EN.shp")

shapefiles_canada_2021 <- read_sf("FED_CA_2021_EN.shp")

tm_shape(shapefiles_canada_2021) +
  tm_polygons()



#3, ANIMATED Graph
  
#install.packages('gganimate')
library(gganimate)
library(grid)
library(gridExtra)
library(cowplot)

# Plot
p <- ggplot(total_data_set,aes(y=Votes.Obtained, x = Province, fill = Party))+
   geom_bar(stat='identity',position = 'dodge',show.legend = FALSE,width=0.6)+ylab('Number of Votes')+ggtitle('Votes in Each Province from 1867 to 2021') 

# Legend
q <- ggplot(total_data_set,aes(y=Votes.Obtained, x = Province, fill = Party))+
   geom_bar(stat='identity',position = 'dodge',show.legend = TRUE,width=0.6)+ylab('Number of Votes')+ggtitle('Votes in Each Province from 1867 to 2021') 

show(q)

#legend <- get_legend(q)  

#grid.newpage()      

#grid.draw(legend)
# need to figure out how to have legend plot with graph


# Animation
anim <- p + transition_time(total_data_set$Year) + labs(title = 'Year: {frame_time}') + view_follow(fixed_y = FALSE,fixed_x = TRUE) 

animate(anim,fps=10,duration=220,height = 600, width =1500)

```

```{r}
canada_ridings_2021 <- sf::read_sf("FED_CA_2021_EN.shp", crs = st_crs(4326)) %>%
  sf::st_transform('+proj=longlat +datum=WGS84')

canada_ridings_2021_map <- leaflet(canada_ridings_2021) %>%
  setView(-80, 35.8, 2.1) %>%
  addProviderTiles("MapBox", options = providerTileOptions(
    id = "mapbox.light",
    accessToken = Sys.getenv('MAPBOX_ACCESS_TOKEN')))

labels <- sprintf("<strong>%s</strong><br/>", canada_ridings_2021$ED_NAMEE) %>% 
  lapply(htmltools::HTML)

canada_ridings_2021_map %>% addPolygons(
  data = canada_ridings_2021,
  weight = 1.25,
  opacity = 1,
  color = "darkgray",
  dashArray = "5",
  fillOpacity = 0.25,
  highlightOptions = highlightOptions(
    weight = 1.5,
    color = "red",
    dashArray = "1",
    fillOpacity = 1,
    bringToFront = TRUE),
   label = labels,
  labelOptions = labelOptions(
    style = list("font-weight" = "normal", padding = "3px 8px"),
    textsize = "15px",
    direction = "auto"))





```